
%create a table figure
f = figure(1);
set(f,'Position',[500 500 300 150]);
dat =  {'        a', 1, '        units';...
        '        b', 2, '        units';...   
        '        c', 3, '        units';...
        '        d',  4, '        units';...
        '        e', 5, '        units';...
        '        f', 6, '        units';};
columnname =   {'Parameter', 'Value', 'Units'};
columnformat = {'char', 'numeric', 'char'}; 
t = uitable('Units','normalized','Position',...
            [0.05 0.05 0.755 0.87], 'Data', dat,... 
            'ColumnName', columnname,...
            'ColumnFormat', columnformat,...
            'RowName',[]); 